spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cwiczenia
    username: mateusz
    password: mateusz
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    log-startup-info: true


